name: Dagboken

on: 
  push:
    branches: [ main ]
  pull_request: 
    branches: [ main ]

jobs: 
  lint_and_test:
    strategy: 
      matrix: 
        os: [ ubuntu-latest, windows-latest, macOS-latest ]

    runs-on: ${{ matrix.os }}

  steps: 
  - uses: actions/checkout@v4 #klonar repot till github actions runner?

  - uses: actions/setup-node@v4 #installerar node
    with: 
      node-version: 22
    chache: 'npm'
  
  - run: npm ci #installera dependencies - clean install

  - run: npm run lint #kör linter

  - run: npm test

  - run: echo "worflow finished" #testar ifall det här gör något